### ISSUE TITLE
Templates: Комната игры

### ISSUE THREAD

**Issue by DotJason** [m20-sch57/labyrinth#12]
Страница, на которой пользователь, находящийся в комнате, может играть в игру.
Технически, каждой комнате можно давать идентификатор, и ставить ей в соответствие страницу игры, URL которой содержит этот самый идентификатор в названии или в качестве параметра.

Страница поделена на несколько частей:
1. Лог игры: главный игровой элемент, где перечислены записи вида: игрок, ход, который он совершил, и результат, к которому этот ход привёл.
2. Панель состояния, где отображается здоровье игрока, количество его пуль и бомб, а также несёт ли он клад.
3. Панель управления, где отображаются кнопки, каждая из которых отвечает за определённый ход.
[4]. "Песочница" а-ля редактор поля, где игрок может, как может, запоминать поле вокруг себя и не только.
[5]. Внутриигровой чат для участников комнаты, разумеется, общий.

**Comment by MaxNacemit** [comment]
Это я вам тоже сверстаю(скрипты, естественно, вешайте сами).

**Comment by gtivansan** [comment]
Максим, не нам, а нам. (Ну ты понял.)

**Comment by MaxNacemit** [comment]
Делать с расчетом на наличие песочницы или на ее отсутствие?

**Comment by gtivansan** [comment]
отсутствие.
