### ISSUE TITLE
Data Base API

### ISSUE THREAD

**Issue by MaxNacemit** [m20-sch57/labyrinth#13]
Есть три базы данных: одна хранит данные профилей игроков, вторая хранит доступные для присоединения в данный момент комнаты, третья хранит данные хранящихся на сервере карт. Общение программы с базой данных происходит с помощью отдельного класса.

**Comment by gtivansan** [comment]
Задача:
чётко описать всё таблицы их внутренность нашей базы данных.
например как в учебнике. [http://ondras.zarovi.cz/sql/demo/](http://ondras.zarovi.cz/sql/demo/
 )
![73551e366bcbb81e973580ae02dfd83d](https://user-images.githubusercontent.com/43723504/48999420-b24b3980-f167-11e8-9332-2d99776236b2.png)

**Comment by MaxNacemit** [comment]
Закоммичено в свою ветку, призываю ознакомиться. Работоспособность кода при наличии sqlite проверена.

**Comment by gtivansan** [comment]
мне кажется, что вот так не делается: `global cursor, conn`

используй лучше `self.cursor` и `self.conn`

**Comment by MaxNacemit** [comment]
> ещё всё-таки жизненно необходим метод `check_password(password_hash)`

А это разве не отдельно делается?

**Comment by yurvor** [comment]
Друзья мои, для подобных обсуждений есть специальный способ - называется pull request. Посмотрите, пожалуйста, это довольно не сложно. Там можно комментировать отдельные части кода и обсуждать, как лучше.
