### ISSUE TITLE
Site: end of the game

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#150]
Нужно сделать так, чтобы сайт адекватно реагировал на конец игры.
Например переносил бы всех игроков обратно в комнату ожидания,
либо переносил бы на какую-нибудь страницу подведения итогов.

**Comment by MaxNacemit** [comment]
Код для собственно завершения игры в модуле лабиринта есть?

**Comment by MaxNacemit** [comment]
Какой файл вообще должен завершать игру?

**Comment by MaxNacemit** [comment]
Где вообще labyrinth.py импортируется? Он вообще где-то используется?

**Comment by gtivansan** [comment]
Отвечаю по порядку.

1. Да
2. Файл не может ничего завершать.
3. файл `routes.py` строчка 3 `from labyrinth_engine import load_lrmap`

**Comment by lounres** [comment]
Ваня, рассказываю: мы без тебя, несколько попыхтев, вроде разобрались, как там связан движок и сервер. Максим вроде бы как раз поправил это, но это не точно. Короче, посмотри [тот самый офигенный](https://github.com/m20-sch57/labyrinth/commit/1cc6e680aed88b002463543c51e6a4a734a6e247) коммит, а именно строки 1 и 250 в `app/routes.py` (на самом деле коммит должен был состоять только из них, но что-то пошло не так).

**Comment by lounres** [comment]
Короче, я поправил Максимов коммит: см. [Site-150-end_of_the_game](https://github.com/m20-sch57/labyrinth/tree/Site-150-end_of_the_game).
Если я накосячил с правками (Максиму): [TEMPorary-(delet_me!)](https://github.com/m20-sch57/labyrinth/tree/TEMPorary-(delet_me!)).

**Comment by lounres** [comment]
И за Максима сделал соответствующий PR. Поскольку я не уверен, что понимаю, как оно работает, я просто оставлю это здесь.
