### ISSUE TITLE
DB bug

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#23]
```
self.cursor.execute('INSERT INTO rooms VALUES (NULL, ?, ?, ?, ?, CURRENT_TIMESTAMP, 1)', room_data)
sqlite3.OperationalError: table rooms has 5 columns but 7 values were supplied
```

почему-то в таблице rooms 5 столбцов.
но их же 7

`self.cursor.execute('CREATE TABLE IF NOT EXISTS rooms (id integer PRIMARY KEY, joinlink text, settings text, description text, players text, cr_date text, pl_num integer)')
`

**Comment by MaxNacemit** [comment]
Это не баг. Используй функцию update_db(), убери и запусти еще раз. Все заработает.

**Comment by gtivansan** [comment]
использовать update_db()  - где?
убрать что?

ошибка тут.
routes.py 
80 - dbase.add_room(joinlink, players, '', username)

**Comment by MaxNacemit** [comment]
> использовать update_db() - где?
Запусти database.py, написав 
db = Database()
db.update_db()

Потом убери этот код оттуда.
