### ISSUE TITLE
Labyrinth: Logs

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#25]
```python
get_msgs(username: str)
```
Возвращает все сообщения отосланные игроку `username`
```python
get_turns(number: int, username: str)
```		
Возвращает все ходы сделанные игрокам
Возвращает ходы сделанные только указанным игрокам, если указан параметр `username`
Возвращает ход под номером `number` с конца, если указан параметр `number`
Например `get_turns(1, 'Вася')` вернёт последний ход Васи
```python
save(filename)
```
Сохраняет игру в файл `tmp\filename.save.json`

**Comment by gtivansan** [comment]
для начала:

методы:
save/load - для записи и чтения из файлов.

update(turn_info) - для обновления лога.

**Comment by Lounres** [comment]
> потом строчки вида
> username || turn

Тогда уж лучше tuple с двумя строчками: username и turn.

> Logger(self)

А зачем давать Logger Лабиринт?

**Comment by gtivansan** [comment]
> лучше tuple
Не понял. Это же типо формат записи в файл.log - тупо текстовый файл.

> А зачем давать Logger Лабиринт?
Не обязательно так. 
Для того чтобы Logger мог сохранить изначальное состояние лабиринта.
Чтобы потом по логу можно было бы восстановить игру. (полезно же)

**Comment by Lounres** [comment]
> Не обязательно так.
> Для того чтобы Logger мог сохранить изначальное состояние лабиринта.
> Чтобы потом по логу можно было бы восстановить игру. (полезно же)

А, так-то да. Я не думал, что чтобы только сохранить.

> Это же типо формат записи в файл.log - тупо текстовый файл.

Теперь я не понял. Logger - это класс, хранящий данные, или что?

**Comment by gtivansan** [comment]
Logger - это класс хранящий данные. Он инициализируется при создании лабиринта

методы load/save позволяют считать/записать всю необходимую информацию в соотв. файл.

**Comment by gtivansan** [comment]
Я немного подумал. Возможно не стоит делать отдельный класс, а просто доделать методов к самому лабиринту.
