### ISSUE TITLE
Site: хранение активных игр

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#26]
словарь
ключ - какой-нибудь id игры
значение - элемент класса Labyrinth

**Comment by MaxNacemit** [comment]
Зачем словарь? Можно хранить объект игры в таблице комнат.

**Comment by gtivansan** [comment]
в базе данных?
так не получится.

**Comment by MaxNacemit** [comment]
Почему же? Ставим строку game, для неактивных она None, для активных - ссылка на объект класса Labyrinth.

**Comment by gtivansan** [comment]
>  ссылка на объект класса Labyrinth

и что это за ссылка?
где расположен элемент, на который она указывает? (спойлер: в словаре)

т.е от того, что в базе данных лежит какая-то там ссылка, проблема расположения лабиринта не решается.
