### ISSUE TITLE
Labyrinth: gun ,arsenal, mediacal_room

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#27]
class gun
class arsenal
class medical_room

**Comment by gtivansan** [comment]
Глеб, хотел бы убедиться в том, что ты не собираешься сделать один pull request на все issues про labyrinth-module
Желательно, чтобы в каждом pull request было не сильно много изменений. (т.е. были бы только изменения соответствующие одному issue)
Тогда всем будет легко понять, что изменилось и как, и высказать своё мнение по этому поводу. 

Если ты считаешь, что сделал ls_weapon, то сделай pull request с изменениями только по теме ls_weapon.

И желательно для каждого issues свою ветку (, но, видимо, в данном случае не обязательно)

**Comment by Lounres** [comment]
Спасибо за информацию. Просто не разобрался, что такое pull request и с чем его едят.
Увы придётся сделать достаточно большой pull request, поскольку я поздно со всем разобрался, а изменения объединяют сущности сразу двух issues.
Заранее простите. Дурак, не разобрался.

**Comment by gtivansan** [comment]
Что такое INITAL_STATES.  
Что происходит, если один модуль использует состояния пересекающиеся с другим?
