### ISSUE TITLE
Labyrinth: properties

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#28]
Придумать, как организовать возможность добавления игроку различных статусов.
Например: кол-во жизней, патронов.

**Comment by MaxNacemit** [comment]
Можно хранить их среди прочих данных комнаты.

**Comment by Lounres** [comment]
Т.к. статус игрока - достояние (дело) самого игрока, то стоит это хранить, как аргументы (или словарь) с состояниями. Такс и было реализовано.

**Comment by gtivansan** [comment]
Идея была в том, чтобы была какая-нибудь функция, возвращающая список состояний.
Тогда потом можно будет реализовать табло, на котором всё это будет отображаться

**Comment by Lounres** [comment]
А чем не player.states.values?

**Comment by Lounres** [comment]
А, я понял.

**Comment by Lounres** [comment]
> Идея была в том, чтобы была какая-нибудь функция, возвращающая список состояний.
> Тогда потом можно будет реализовать табло, на котором всё это будет отображаться

В каком виде функция должна возвращать статусы? В виде списка или как?

**Comment by gtivansan** [comment]
В этом состоит задача. Чётко представить себе что, где, когда, и в каком формате происходит.

**Comment by gtivansan** [comment]
примерно
```python
class Property:
	def new_property_bar(self, property_type, ...):
		if hasattr(self, bars):
			self.bars.add(...)
		else:
			self.bars = {...}

	def new_property(self, property_name):
		pass

class Health(Property):
	def __init__(self, player):
		self.player = player
		self.new_property('health') # health is int
		self.new_property_bar('health'...)

	def hurt()
		self.player.health -= 1
```

**Comment by gtivansan** [comment]
Я понемногу думаю, как бы всё это реализовать. Пока вот:
```python
# property box is imaginary box with some properties and property-bars
class PropertyBox:
    def new_property_bar(self, property_name, some_ui_info):
        if property_name not in self.properties:
            error()

    def new_property(self, property_name, ...):
        ...
        return Property(...)

# area: ui description
# like buttons
class PropertyBar:
    pass


class Property:
    def __init__(self, init_value, name):
        self.value = init_value
        self.name = name

    def set_value(self, new_value):
        self.value = new_value

    def get_value(self):
        return self.value

class Health(PropertyBox):
    def __init__(self, init_health=2):
        self.health = self.new_property('health', init_health)
        self.new_property_bar('health', some_ui_info)

    def hurt()
        hp = self.health.get_value()
        self.health.set_value(hp - 1)

        if hp == 1:
            kill_player()


# how to hurt:
player.get_property(Health).hurt()
```

**Comment by gtivansan** [comment]
Я ещё немного подумал. Думаю можно сделать `property` объектом лабиринта по аналогии с  `item`, `location`, `player` и  `npc`.

А соответственно `property_bar` по аналогии с `buttons`.

Тогда ранение игрока будет выглядеть примерно так:
```python
player.get_children(cls = Health).hurt()
```
Это если для каждого игрока свой `Health` делать.
А если общий, то так:

```python
labyrinth.get_object(cls = Health).hurt(player)
```
