### ISSUE TITLE
Шапка

### ISSUE THREAD

**Issue by DotJason** [m20-sch57/labyrinth#3]
Шапка отображается на всех страницах сверху и содержит:

1. Название проекта: а куда мы, собственно, попали?
[2]. Логотип: простой и запоминающийся.
3. Список всех важных страниц сайта. Естественно, настраиваемый и расширяемый, а не захардкоженный.

**Comment by gtivansan** [comment]
Нужна ли шапка на всех страницах?
Я почти уверен, что внутри комнаты показывать шапку точно не стоит. (Ибо мешает)
Хотя какой-нибудь минималистичный вариант, аля пара маленьких кнопок где-то сверху, наверное всё-таки нужен.

**Comment by MaxNacemit** [comment]
Вся шапка в том виде, в каком она у меня есть сейчас и есть четыре маленьких ссылки и вряд ли она будет сильно больше.
