### ISSUE TITLE
Labyrinth: хранение карт

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#30]
```python
load_lrsave(loadfile: str, savefile: str)
```
Функция. Загружает игру из файла `loadfile` и возвращает объект класса `labyrinth`
Игра будет сохраняться в файл `savefile`
```python
load_lrmap(loadfile: str, savefile: str, users: list of str)
```
Функция. Возвращает объект лабиринта с картой из файла `loadfile` и с игроками `users`
Игра будет сохраняться в файл `savefile`

**Comment by MaxNacemit** [comment]
Объясни, пожалуйста, зачем тут JSON и что это такое. Я в последнее время совсем перестал понимать происходящее.

**Comment by gtivansan** [comment]
JSON
Текстовый формат обмена данными, основанный на JavaScript. 

Поскольку карту нужно будет хранить в каком-нибудь формате,
возможно, имеет смысл делать это именно в формате json т.к. это потом будет удобно 
для редактора карт.

**Comment by gtivansan** [comment]
Пример формата.
[map_format.json.txt](https://github.com/m20-sch57/labyrinth/files/2769155/map_format.json.txt)
