### ISSUE TITLE
Templates: Комната набора игроков

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#32]
Именно в этой комнате можно менять настройки игры.
Здесь собираются игроки перед игрой.
Здесь они оказываются после игры.

**Comment by MaxNacemit** [comment]
Уже думаю над этим.

**Comment by gtivansan** [comment]
Ну ведь надо же после игры какой-нибудь итог подводить.
И вдруг те же люди захотят сыграть вторую партию.
И чтобы были все эти возможности их нужно возвращать в их комнату набора.

**Comment by MaxNacemit** [comment]
Понял, запилю.

**Comment by MaxNacemit** [comment]
Зачем плодить домены, когда можно грузить разное на /room/<room_link> в зависимости от наличия или отстутствия объекта игры?

**Comment by gtivansan** [comment]
так то всё можно грузить в /<smth> и в зависимости от smth что-то отвечать.
и будет одна функция вместо наших 10, но надо ли?

комната набора и комната игры работают по разному, так давай давать им разные пути.
Я предлагаю заменить room на 
/waiting_room/<smth>
/game_room/<smth>

Либо можно так:
/room/waiting/<smth>
/room/game/<smth>

**Comment by MaxNacemit** [comment]
Тогда просто еще надо будет впилить редирект на /game_room/ с /waiting_room/ при заполнении комнаты.

**Comment by gtivansan** [comment]
Вроде просто должна быть кнопочка "начать игру"

**Comment by MaxNacemit** [comment]
Дизайн есть, верстка тоже, но мне нужен рабочий db_api, чтобы это протестировать.

**Comment by gtivansan** [comment]
Супер. Закомить в отдельную ветку. Как-нибудь присоединим.

**Comment by MaxNacemit** [comment]
Скрипт для настроек сам воткнёшь?

**Comment by gtivansan** [comment]
Отправь темплейт, я в него вмёржу скрипт. Он уже почти есть.
