### ISSUE TITLE
Labyrinth:  клад, река, устье, арсенал, мёдпункт, медвед

### ISSUE THREAD

**Issue by Lounres** [m20-sch57/labyrinth#35]
Сделать локации: клад, река, устье, арсенал, мёдпункт, медвед.

**Comment by gtivansan** [comment]
клад, медведь - не локации

насколько я понимаю, река+устье работают также как яма.  (они все работают как телепорт)

**Comment by Lounres** [comment]
Место, где хранится клад - локация. Так же вопрос: клад берётся сам или это отдельное действие на целый ход?
Про медведа - понял, принял.

**Comment by Lounres** [comment]
Так же правильно я понимаю, что при ранении клад выпадает и остаётся в локации, где выпал?

**Comment by gtivansan** [comment]
> Место, где хранится клад - локация

Клад не лежит где-то, потому что это место специально для него, а лежит где-то, потому что должен где-то лежать. И тем более его место нахождения не зафиксировано. (Его могут сначала взять, а потом где-то обронить). Потому эту часть про то, что клад - локация, я не понял.

>  Так же вопрос: клад берётся сам или это отдельное действие на целый ход?

Думаю, что лучше сделать отдельное действие.

> правильно я понимаю, что при ранении клад выпадает и остаётся в локации, где выпал?

есть 2 варианта:

- предметы выпадают при ранении
- предметы не выпадают при ранении

К каждому предмету, для которого выпадение может быть разумным, надо сделать настройку выпадения предмета при ранении

**Comment by Lounres** [comment]
Ещё такой момент: если игрок сходил в стену, медведь стоит на месте или идёт в том же направлении?

**Comment by Lounres** [comment]
Ещё вопрос: медведь чувствует пули? Можно ли его убить?

**Comment by Lounres** [comment]
Ещё вопрос: мёдпункт лечит медведей?

**Comment by MaxNacemit** [comment]
Нет.

**Comment by Lounres** [comment]
ОК.

**Comment by Lounres** [comment]
И ещё вопрос: если игрок/медвед попал в яму 1 и оказался в яме 2, то он ведь не должен проваливаться в яму 2, если останется на месте? А если на следующий ход пойдёт в соседнюю клетку, которая будет ямой 3, то тогда он ведь должен провалиться?

**Comment by Lounres** [comment]
Новый вопрос: что такое выход? Если воспринимать его, как локацию, то какими свойствами он обладает: может ли в него, например, выйти NPC?

**Comment by gtivansan** [comment]
Я тут в процессе тестирования понял, что стена у нас всё-рано очень странная получилась.
~~Я тебе насоветовал, а ты сделал.)~~

Теперь мне кажется, что разумно сделать так:
У стены тоже есть соседи, а когда её взрывают, она просматривает список локаций, и если встречает объект `L`, у которого в направлении `dir` она сама, то если `dir` есть в списке направлений этой стены, она устанавливает `parent` локации `L` равным `self.get_neighbour(dir)`,  а если нет, то равным `Outside`.
