### ISSUE TITLE
Labyrinth: разделение по файлам

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#36]
Можно я буду топить за разделение объектов в файлы по смыслу?

**Comment by MaxNacemit** [comment]
В Мега-Учебнике это было. Мне кажется, это надо будет делать, когда все заработает.

**Comment by gtivansan** [comment]
В мега-учебнике этого не могло быть, потому что обсуждается устройство модуля лабиринта, с сайтом не связанного пока никак.

Если что, файлы, про которые идёт речь, это файлы в папке labyrinth, начинающиеся с LS

**Comment by Lounres** [comment]
Я решил согласиться с Ваней. В следующих коммитах поменяю.
