### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#37]
Правильно ли я понимаю, что в таблице комнаты НЕ хранится список игроков, 
но вот у игрока, комната, в которой он находится, всё-таки хранится?

**Comment by MaxNacemit** [comment]
Именно.

**Comment by gtivansan** [comment]
Это очень плохо. Откуда мне брать список игроков в комнате?

**Comment by MaxNacemit** [comment]
self.cursor.execute('SELECT FROM users WHERE room=<id>')
Не благодари.

**Comment by MaxNacemit** [comment]
Будет закоммичено.

**Comment by gtivansan** [comment]
Верно ли я понимаю, что чтобы что-то поменять в таблице, ты удалял строчку, и вставлял другую?

А как же вот так писать:
`UPDATE table_name SET param = value WHERE ...`

**Comment by gtivansan** [comment]
в таблице rooms нужно ещё name, users
joinlink не нужен т.к. это будет id комнаты   (в таком виде; WjVvs37t)

**Comment by gtivansan** [comment]
Я сам починю.

**Comment by MaxNacemit** [comment]
NULL - это число, на единицу большее максимума.

**Comment by gtivansan** [comment]
так-то NULL означает, что в соотв. месте значение пустое, т.е. ничего не хранится.
чтобы число увеличивалось на 1 нужно писать autoincrement.

про users не понял вопроса.

**Comment by MaxNacemit** [comment]
NULL для целого типа дает именно то, что надо.

**Comment by gtivansan** [comment]
Ну может быть и так, но 
1 это было бы странно
2 я нигде такого не видел
3 специально для того, чтобы номер увеличивался на 1 существует autoincrement

**Comment by MaxNacemit** [comment]
В теории она как раз и должна работать нормально, ибо после удаления комнаты тебя перекидывает на список комнат, и страницы перегружаются.

**Comment by MaxNacemit** [comment]
В моей книге про autoincrement ничего не было, и был NULL.

**Comment by gtivansan** [comment]
В мире существует не только твоя книга.  (Дал бы тогда хотя бы ссылку, чтобы я увидел, как именно там это делается.)

**Comment by gtivansan** [comment]
>В теории она как раз и должна работать нормально, ибо после удаления комнаты тебя перекидывает на список комнат, и страницы перегружаются.

Проблема не в перекидывании, а в том, что ты отсекаешь комнаты по номеру, но если вдруг удалится какая-нибудь комната, эти номера никто не сдвинет.

**Comment by MaxNacemit** [comment]
Номера никто не сдвинет, но не будет ссылок на отсутсвующие номера.

**Comment by gtivansan** [comment]
А всё, сорян. Я неправильно понял, как оно работал.
И работало оно действительно нормально.
