### ISSUE TITLE
где будут настройки, при создании комнаты

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#42]

**Comment by MaxNacemit** [comment]
Объясняю. Если сделать настройки при создании, можно будет заполнить форму, нажать кнопку, и все заработает. А если сначала создавать комнату, а потом ее настраивать, мы наплодим формы и трудности для юзера без какой-то великой цели.

**Comment by gtivansan** [comment]
Если у пользователя проблема что-то найти, то это связанно не с тем, что мы ему не дали возможность настроить комнату сразу, а стем, что информация на сайте расположена криво.

Кто вообще сказал, что пользователь захочет добавлять описание или что-то такое.
Зачем его заставлять это делать?

**Comment by MaxNacemit** [comment]
Если юзер не хочет добавлять описание - без проблем, это не обязательное поле. Обязательно ему только ссылку указать.
