### ISSUE TITLE
Labyrinth: to fix

### ISSUE THREAD

**Issue by Lounres** [m20-sch57/labyrinth#49]
- [ ] 1) доработать ошибки;
- [ ] 2) понаделать по возможности ошибок;
- [ ] 3) разобраться с Ваниным предложением про декоратор;
- [ ] 4) подпилить gameAPI;
- [x] 5) ~~исправить найденные баги;~~
- [x] 6) ~~исправить проблемы с ID.~~
- [ ] 7) исправить состояния игрока.

Баги:
- [x] 1) ~~объединить итерации для всех типов объектов;~~
- [x] 2) ~~убрать перебор случаев в Wall и GlobalWall;~~
- [x] 3) ~~удалить Hole.be_swallowed;~~
- [x] 4) ~~заменить Player.in_hands функцией;~~
- [x] 5) ~~исправить `Wall.__init__`;~~
- [x] 6) ~~исправить функции Treasure;~~

**Comment by gtivansan** [comment]
Предлагаю такой план действий. Пусть PR на ls_weapon пока висит, а сейчас надо 
1) сделать всё, что к issues из этого PR не относится, по очереди.
2) сделать на каждое такое изменение PR, желательно по очереди, чтобы потом не запутаться при merge.
3) обсудить все вопросы, которые появятся, в соответствующих теме PR
4) по очереди их всех приmergить
5) потом приmergить PR про ls_weapon ls_locations

**Comment by gtivansan** [comment]
Т.е сначала сделать какие-то глобальные штуки, а потом уже те штуки, которые от глобальных зависят.

**Comment by Lounres** [comment]
ОК.

**Comment by gtivansan** [comment]
И про всякие концептуальные штуки:
1 - придумать.
2 - оформить в текстовом виде.
2 - обсудить до полного соглашения
3 - написать в программном виде. 
4 - PR
5 - обсудить до полного соглашения
6 - merge

**Comment by Lounres** [comment]
ОК.

**Comment by gtivansan** [comment]
Я понял, что вместо того, чтобы писать
```python
try:
    self.turn_set
except:
    ...
```
можно объявить `turn_set`, как атрибут класса, а не экземпляра:
```python
class LabyrinthObject:
    turn_set = {}
    ...
```
Тогда если `turn_set` не определен, как атрибут экземпляра, будет взято значение атрибута класса равное `{}`

**Comment by gtivansan** [comment]
Вот картинка для понимания.
![image](https://user-images.githubusercontent.com/43723504/51040667-2717ed00-15c9-11e9-8442-157cffb18962.png)

**Comment by gtivansan** [comment]
Ок я понял. Тогда надо сделать через `hasattr`
