### ISSUE TITLE
Site: is_authenticated

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#50]
декоратор для закрытия доступа к странице неавторизованных пользователей.

**Comment by MaxNacemit** [comment]
Беру.

**Comment by MaxNacemit** [comment]
Вопрос: что нам надо? Нам надо, чтобы неавторизованные пользователи не имели доступа к каким страницам?

**Comment by gtivansan** [comment]
Чтобы их переключало на главную.

**Comment by MaxNacemit** [comment]
Это я понял, вопрос в том, откуда их должно перекидывать.

**Comment by gtivansan** [comment]
оттуда, где использован декоратор.
