### ISSUE TITLE
bugs and bad code style

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#52]
BUGS

labyrinth_list.py
-забыл self в методах

Labyrinth/game.py
-исправить работу to_send

app/tremplates/base.html
-два раза проверка на наличие шапки

CODE STYLE

templates
-в HTML лучше использовать " вместо ' 
-использовать два пробела для отступов

**Comment by MaxNacemit** [comment]
Баг: приложение не запускается на хосте 0.0.0.0, так как веб-сокет запускается на 127.0.0.1. Надо пофиксить, я без этого запустить его не могу.

**Comment by gtivansan** [comment]
В какой ветке это происходит?

**Comment by MaxNacemit** [comment]
В мастере

**Comment by gtivansan** [comment]
Как ты пытаешься запустить сайт?
Что при этом происходит?

> веб-сокет запускается на 127.0.0.1.

что ты тут имел в виду?

P.S.
У меня всё запускается.

**Comment by MaxNacemit** [comment]
Я запускаю flask run --host="0.0.0.0", а мне говорит, что web socket running at 127.0.0.1. И виртуалка не открывается.

**Comment by gtivansan** [comment]
можно скрин?

> И виртуалка не открывается.

что такое виртуалка?

**Comment by MaxNacemit** [comment]
У меня приложение codeanywhere на айпад, оно запускает код с виртуальной машины. Скрин пока нельзя, у меня бесплатное время закончилось.

**Comment by MaxNacemit** [comment]
Как бонус: невозможно отключить дебаггер.

**Comment by gtivansan** [comment]
?  убрать `debug=True` в `app.__init__`
