### ISSUE TITLE
Labyrinth: id problems

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#55]
### Задача: 
целиком избавиться от всяких ObjectID.

**Comment by gtivansan** [comment]
Наверно будет хорошо, если при инициализации карты всем объектам будет определён тип.
тип один из player; location; item; npc;

**Comment by gtivansan** [comment]
И про поле.

Можно попробовать сделать так:
1. Избавиться от класса field.
2. Передать классу labyrinth лист локаций, лист/set предметов, лист npc, лист игроков, лист связности по номерам, которые в этих листах.
3. Внутри класса labyrinth 
-каждому объекту, которому нужен parent, установить его 
-каждой локации создать атрибут directions - словарь из пар (направление, локация)
-сохранить set объектов каждого типа, чтобы по необходимости их можно было бы получить.

**Comment by Lounres** [comment]
> Наверно будет хорошо, если при инициализации карты всем объектам будет определён тип.
> тип один из player; location; item; npc;

Да, мне тоже кажется. Мне кажется, что здесь можно с классом для типа не заморачиваться, а написать его как защищённый атрибут самого объекта. Например:
```
some_LO.type = 'its_type'
```

**Comment by Lounres** [comment]
> И про поле.
> 
> Можно попробовать сделать так:
> 
>     1. Избавиться от класса field.
> 
>     2. Передать классу labyrinth лист локаций, лист/set предметов, лист npc, лист игроков, лист связности по номерам, которые в этих листах.
> 
>     3. Внутри класса labyrinth
>        -каждому объекту, которому нужен parent, установить его
>        -каждой локации создать атрибут directions - словарь из пар (направление, локация)
>        -сохранить set объектов каждого типа, чтобы по необходимости их можно было бы получить.

Мне нравится. Я подумаю, но, скорее всего, это лучшее решение проблемы.

**Comment by gtivansan** [comment]
> защищённый атрибут самого объекта

ты имеешь в виду вот это?:
```
LO._protected
LO.__privat
```

**Comment by Lounres** [comment]
> ты имеешь в виду вот это?:
> 
> ```
> LO._protected
> LO.__privat
> ```

Да, именно.



> obj._type = 'location'

Нет, совсем нет. Посмотри вот [это](https://docs.python.org/3/library/functions.html?highlight=property#property).



> А про нижние подчеркивания: у питонистов есть какое-то соглашение по поводу того, что таким образом обозначается.

Вроде бы обычные атрибуты можно использовать, как угодно, с одним подчёркиванием  - защищённые, т.е. с ними нельзя делать, что попало, а с двумя - неизменяемые и неудаляемые. Это, как мне кажется.

**Comment by gtivansan** [comment]
> Вроде бы обычные атрибуты можно использовать, как угодно, с одним подчёркиванием - защищённые, т.е. с ними нельзя делать, что попало, а с двумя - неизменяемые и неудаляемые. Это, как мне кажется.

Вроде делать можешь всё что хочешь, но принято что, ...

**Comment by Lounres** [comment]
Ну, да. Я это имел в виду.
