### ISSUE TITLE
Показ формы настроек скриптом

### ISSUE THREAD

**Issue by MaxNacemit** [m20-sch57/labyrinth#59]
Настройки комнаты должны показываться скриптом, привязанным к кнопке "Настройки комнаты", но они показываются под кнопками.

**Comment by gtivansan** [comment]
У меня есть идея:

Можно сделать так, чтобы можно было бы менять название и описание просто нажав на название или описание.

Т.е есть название. Если на него нажать появляется прямоугольничек, и можно редактировать.

Про то, что сейчас:

Поскольку не было никакого файла/темплейта, в котором было бы всё кроме возможности менять название/описание, я добавил эту возможность самым простым образом.Т.е просто добавив поля для смены названия и описания.

Если проблема в том, что при нажатии на кнопку должно что-то происходить, то тебе, как человеку, формирующему внешний вид нашего сайта, нужно либо самому добавить возможность нажимания на кнопку, либо не делать это самому (видимо интересен именно этот вариант), но тогда тебе нужно описать, что именно должно происходить и сделать все необходимые темплейты. Если в них есть какие-то части, которые будут меняться со временем (например список игроков) тебе нужно заполнить эти части какими-нибудь примерами (например для списка игроков нужно придумать внешний вид, если в этом списке конкретно Петя и Вася), чтобы потом, человек, который будет писать скрипт или что-то ещё, что должно оживить эту часть странички, понимал где и как именно ему нужно что-нибудь менять.

Конкретно сейчас, могу попробовать сделать так, чтобы поля смены названия и описания пропадали/появлялись при нажатии на кнопку настройки.

**Comment by MaxNacemit** [comment]
У меня там был скрипт onClick. По нажатию на кнопку он должен был менять HTML room-info на HTML формы. Там надо было только разумно вставить HTML формы, все.

**Comment by gtivansan** [comment]
> только разумно вставить HTML формы, все

А вот этот html ты должен был написать, чтобы понятно было откуда что брать, и где что менять.

И кстати не onClick, а onclick

 > должен был менять HTML room-info на HTML формы

Так настройки показывать в room_info?

**Comment by MaxNacemit** [comment]
Да. Форма та же, просто лежит в room-info и показывается только при нажатии кнопки.

**Comment by gtivansan** [comment]
room-info скрывать?  или просто дорисовывать форму?

**Comment by MaxNacemit** [comment]
Скрывать.

**Comment by MaxNacemit** [comment]
И что это такое?
![9a44964e-871c-44e0-a3cf-08ce4ba6d5ae](https://user-images.githubusercontent.com/43728459/51334197-5b3f5200-1a90-11e9-98f0-91297219ae05.png)

**Comment by MaxNacemit** [comment]
В фаерфоксе они выделяются при наведении, но все равно форма расположена так, как на скрине.

**Comment by gtivansan** [comment]
Ты уверен, что запускаешь master?

Т,е у меня таких проблем нет. Я даже firefox скачал, чтобы протестить. Всё нормально.

**Comment by MaxNacemit** [comment]
Абсолютно. Могу показать завтра или в субботу.

**Comment by gtivansan** [comment]
Ты скорее всего запускаешь [эту версию](https://github.com/m20-sch57/labyrinth/tree/b44c8166e0e40139fae254f245b333fec8b2f86e)

А вот в ней всё плохо, потому что ты сбросил некоторые изменения своим коммитом.

**Comment by MaxNacemit** [comment]
А как из нее перейти в нормальную версию?

**Comment by gtivansan** [comment]
Просто нужно получить все изменения.
Если ты используешь Git Extensions, то нужно нажать на синюю стрелочку, направленную вниз.

**Comment by MaxNacemit** [comment]
![image](https://user-images.githubusercontent.com/43728459/51335922-4fee2580-1a94-11e9-9ccc-917389c974b0.png)
С компа происходит то же самое, туда я совершенно точно скачал последнюю версию.

**Comment by gtivansan** [comment]
Там есть файл app/static/js/game_room.js ?

**Comment by MaxNacemit** [comment]
Специально переустановил. Теперь вообще вся верстка поехала. game_room.js и toggle.js есть. 
![image](https://user-images.githubusercontent.com/43728459/51336124-d6a30280-1a94-11e9-89af-cc048afa0567.png)

**Comment by gtivansan** [comment]
Нажми ctrl + f5. Всё починится.

**Comment by MaxNacemit** [comment]
С ctrl-f5 работает. Но на айпаде-то f5 нет... Имхо, с этим надо разобраться.

**Comment by gtivansan** [comment]
Сотри кэш.

**Comment by MaxNacemit** [comment]
Алсо, как применять настройки?

**Comment by gtivansan** [comment]
Не понял.

**Comment by MaxNacemit** [comment]
Я вбиваю имя и описание комнаты. Как мне применить его к комнате?

**Comment by gtivansan** [comment]
энтер нажать

**Comment by MaxNacemit** [comment]
Очень неинтуитивно. Подсказку бы под формой, что-то вроде "Нажмите Enter в поле ввода имени, чтобы применить настройки". А лучше кнопку запилить.

**Comment by gtivansan** [comment]
Будет вам кнопка.
