### ISSUE TITLE
Labyrinth: end of the game

### ISSUE THREAD

**Issue by lounres** [m20-sch57/labyrinth#65]
Научиться заканчивать игру.

**Comment by Lounres** [comment]
У меня есть такая идея.

Во-первых, сделать ещё одного получателя - `$system$`, для того, чтобы система (точнее говоря сервер) получала какую-либо важную информацию. В данный момент мне требуется это, чтобы отправить ей сообщение о том, что игра закончена, поскольку игра может продолжаться до бесконечности. Можно это попытаться сделать через файлы логов, которые система будет время от времени читать и будет реагировать, если надо.

Во-вторых, предлагаю сделать у `Labyrinth` метод `end_the_game`, который будет принимать победителя в виде аргумента `winner` и, если он не равен `None`, то будет отправлять игроку в этом аргументе сообщение о победе, а остальным сообщение о проигрыше, иначе будет всем отправлять сообщение о ничьей. А системе метод отправит сообщение о конце игры. И тогда каждый раз, когда будет понятно (или можно предположить), что игра закончилась, вызывать эту функцию.

Также можно сделать аргумент(ы) для особых сообщений. Например, если последний игрок умер от пули, то можно написать это. Или если от чего победил победитель (принёс клад в выход первым, убил всех оставшихся и т.п.).

Также я думаю на счёт такого случая: игроки все умерли, но, например, через пару ходов некоторые возродятся (ну написали всякие объекты для возрождения). Тогда стоит написать некоторую функцию проверки, что всё, это конец игры, или ещё есть шанс на продолжение. И тогда либо `end_the_game` сама будет использовать функцию, либо эта фунцкия будет использована перед использованием `end_the_game`. (Мне кажется, что лучше первое.) Например:
```
class Labyrinth:
...
    def end_the_game(self, winner=None):
        if self.is_it_time_to_end():
            [всякое тело с тем, что надо сделать]
...
    def is_it_time_to_end(self):
        [всякое тело с проверкой того, конец ли игры это]
```

**Comment by gtivansan** [comment]
> Во-первых, сделать ещё одного получателя

Можно и без этого. Нужно всего лишь чтобы get_active_player() сообщало о конце игры, а не об активном игроке если игра закончилась.

Про всякие нетривиальные способы закончить игру.
Можно просто сделать метод `end_game`, а если нужно, чтобы игра заканчивалась, когда все игроки умерли то нужно добавить в игру объект `death_refery`, который заканчивает игру, если все игроки мерты [и никто не собирается возрождаться]

**Comment by gtivansan** [comment]
> Ну такое себе. Функция тогда не делает то, на что она была рассчитана (только на определение активного игрока, если таковой есть). Также как она будет понимать, закончилась ли игра?

Ну тогда она может возвращать None. Это логично в том смысле, что после конца игры нет активных игроков.

> Что такое "refery"?

Там опечатка. не refery а referee - спортивный судья.

> А я что предлагаю? Не то же ли самое

Я хотел сделать акцент на слово просто.

**Comment by Lounres** [comment]
> Ну тогда она может возвращать None. Это логично в том смысле, что после конца игры нет активных игроков.

Именно так я уже её реализовал у себя (но пока не коммитил, даже локально).

> Я хотел сделать акцент на слово просто.

А, ОК.
