### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#66]
Я пытался добавить database.db в gitignore всякими разными способами, но у меня не получилось.

Что делать?

**Comment by Lounres** [comment]
А что ты в итоге сделал? Мне тоже интересно.

**Comment by gtivansan** [comment]
Надо было сам файл ещё удалить. Если он уже есть в репозитории, то никакие gitignore не спасут, и он будет обновляться.

**Comment by Lounres** [comment]
Ясно.
