### ISSUE TITLE
Лабиринт перестаёт отправлять сообщения.

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#69]
Лабиринт перестаёт отправлять сообщения, если создать две комнаты и начать переходить между ними.

Я пока не понял в чём проблема.

**Comment by MaxNacemit** [comment]
Э... Мы же играем в одной комнате одновременно?

**Comment by gtivansan** [comment]
Ты можешь выйти из одной и войти в другую.

**Comment by gtivansan** [comment]
Всё. Я починил. Там слишком идейно.
