### ISSUE TITLE
Создание игры

### ISSUE THREAD

**Issue by DotJason** [m20-sch57/labyrinth#7]
Страница создания пользователем своей игровой комнаты.

На ней отображаются настройки комнаты:
1. Название.
2. Описание.
3. Выбранное поле (из списка сохранённых лабиринтов пользователя, либо случайное).
4. Максимальное количество игроков.

**Comment by gtivansan** [comment]
опционально:

5. Открытая/Закрытая игра.
6. Ссылка на комнату.
7. Отправка приглашения в игру другу.
