### ISSUE TITLE
mistake in hurt_player

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#71]
строка 28
```python
            self.labyrinth.active_player_number = self.labyrinth.locations.index(active_player)
```

А должно быть
```python
            self.labyrinth.active_player_number = self.labyrinth.players_list.index(active_player)
```

**Comment by Lounres** [comment]
> А должно быть

Да, конечно, это опечатка.

> И может мне показалось, но в момент, когда убиваешь другого игрока приходит сообщение Пиф-паф, ой-ой-ой. Снаряд попал в . без ника убитого игрока

Да, я нашёл баг. Поменяй строку 82 на такую:
```
            kicked_players = set(filter(lambda obj: obj.type in ['player', 'dead_player'], kicked_characters))
```

**Comment by Lounres** [comment]
Да, я тоже заметил.
