### ISSUE TITLE
Starting up local server.

### ISSUE THREAD

**Issue by Lounres** [m20-sch57/labyrinth#76]
Как сервак поднимать? По-старому в консоли ввести "flask run" не особо работает. Или вы запускаете не локальные сервера?

**Comment by gtivansan** [comment]
`socketio.run(app, host="0.0.0.0", port=3000,)`
замени на
`socketio.run(app)`

либо тебе нужно посмотреть свой IPv4-адрес.  Для этого существует команда ipconfig
Сайт будет доступен по адресу  IPv4:port

**Comment by MaxNacemit** [comment]
Я делаю flask run, и на 127.0.0.1 все доступно.

**Comment by gtivansan** [comment]
Но только порт указанный нужно вбивать. Т.е 3000
