### ISSUE TITLE
Новый дизайн и исправление верстки под 4:3

### ISSUE THREAD

**Issue by MaxNacemit** [m20-sch57/labyrinth#80]
- Нарисовать новый дизайн
- Исправить верстку под устройства 4:3, чтобы вводы форм не выезжали из сайдбаров.

**Comment by gtivansan** [comment]
С чем связан такой интерес к устройствам именно 4:3
Может сделать, чтобы везде работало?

**Comment by MaxNacemit** [comment]
На 16:9 и так работает.
