### ISSUE TITLE
Фича: Аватарки

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#84]
Возможность поставить, сменить аватарку.
Отображение аватарки в разных местах.

Можно использовать Gravatar.
У них в принципе идея классная. (одна аватарка на все сервисы), но для нас облегчения т.к. не нужно будет хранить картинки на сервере.

**Comment by MaxNacemit** [comment]
С Gravatar проблема одна: про него знают **далеко** не все, поэтому для залива аватарки мы сделаем еще одну регистрацию. Мне кажется, это неправильно. Место на сервере is not an issue - картинки будут уменьшаться до отображаемого размера при загрузке(а он будет рассчитываться, чтобы влезать рядом с сообщением, а это максимум 100 на 100). Нам же не нужно будет давать выгружать их обратно?
