### ISSUE TITLE
Site: enter_game use cases

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/labyrinth#88]
Описать UC для игровых комнат. Решить что делать, если человек вошёл в несколько комнат, как начинается игра, какие-нибудь оповещения и т.д.

Текущий вариант:

1. Пользователь может зайти в комнату.
2. В комнате ему доступны: 
    * список людей
    * кнопка выхода
3. Он может покинуть комнату (чтобы почитать правила, ...).
4. Он по прежнему будет оставаться в комнате если
    * Он покинул комнату не через кнопку выхода
    * Он не зашёл в какую-либо ещё комнату.
5. В момент начала игры:
    * все пользователи с открытой вкладкой комнаты переходят в игру
    * всем пользователям, присутствие в комнате которых обусловлено пунктом 4, отсылается уведомление о начале игры с возможность начать и не начать.
    * если пользователь начал игру, но также присутствовал в какой-либо ещё комнате, это присутствие никак не карается. пользователь имеет право играть сразу в несколько игр.

**Comment by MaxNacemit** [comment]
>если человек вошел в несколько комнат
Не войдет(по той простой причине, что смотреть что-то кроме комнаты в той же вкладке, если ты в комнате, нельзя). Для многовкладочников надо будет запилить предупреждение. 
>как начинается игра
При заполнении комнаты отсчитываем 10 секунд, если все на месте, начинаем.

**Comment by gtivansan** [comment]
Максим, 

У меня просьба. Не пиши ни про какое своё  необсуждённое хоть с кем-то представление о чём-либо в формате "так будет".  У меня есть два аргумента, почему так не стоит делать:
1. Это будет путать того, кто читает и не в теме.
2. Это просто не правильно. Ты не можешь утверждать, что что-то будет так-то только потому, что ты так решил. Правильнее было бы просто как-то объявить о своём мнение окружающим.

Кроме этого, заметь, твой ответ не является ответом на поставленный вопрос.

Из написанного тобой кратко и по делу:

- Предупреждение, в случае попытки зайти во вторую комнату.
- Старт игры через 10с в случае полного заполнения комнаты.

Моё видение в том, что не стоит запрещать людям заходить в несколько комнат.
Но и поторапливать поскорее их поиграть тоже, мне кажется не стоит.

_Я замечу, что четыре строчки выше являются моим и твоим мнением, что придаёт им статус того, что нужно **обсудить**, а не того, чему нужно бездумно следовать, или в чём нужно бездумно убеждать других_

Моё видение UC:

1. Пользователь может зайти в комнату. 
2. В комнате ему доступны:
     - список людей  
     - кнопка выхода
3. Он может покинуть комнату (чтобы почитать правила, ...).
4. Он по прежнему будет оставаться в комнате если
    - Он покинул комнату не через кнопку выхода
    - Он не зашёл в какую-либо ещё комнату.
5. В момент начала игры:
    - все пользователи с открытой вкладкой комнаты переходят в игру
    - всем пользователям, присутствие в комнате которых обусловлено пунктом 4, отсылается уведомление о начале игры с возможность начать и не начать.
    - если пользователь начал игру, но также присутствовал в какой-либо ещё комнате, это присутствие никак не карается. пользователь имеет право играть сразу в несколько игр.

_Я обязательно что-нибудь забыл в этом списке, поэтому ещё раз повторюсь. Это то, что нужно обсудить, всячески дополнить, и только потом прийти к тому, как действительно будет, на что потом можно будет ссылаться._

P.S. Максим, добавляй пустые строки после цитирования, чтобы можно было отличать, что комментируемое, а что комментарий.

**Comment by MaxNacemit** [comment]
Я не очень представляю(вернее, совсем не представляю) участие в нескольких играх одновременно. Это:
- практически невозможно так, чтобы всем было хорошо - если ход в одной комнате наложится по времени на ход в другой, все остальные в той комнате испытают огорчение. А если комнат 3? 4?
- потребует перепилить кучу кода - сейчас все делается из расчета на то, что можно находиться только в одной комнате
- не очень осмысленно - я не очень представляю себе человека, который может играть в 2-3 стратегических игры и не напрягаться. В остальном согласен.

**Comment by gtivansan** [comment]
> не очень осмысленно - я не очень представляю себе человека, который может играть в 2-3 стратегических игры и не напрягаться. 

Мне не кажется, что лабиринт - это стратегическая игра.

>потребует перепилить кучу кода - сейчас все делается из расчета на то, что можно находиться только в одной комнате

Я не вижу ни одной вещи, которая была бы сделана с таким расчётом. Приведи какой-нибудь пример, если считаешь, что они есть.

> практически невозможно так, чтобы всем было хорошо - если ход в одной комнате наложится по времени на ход в другой, все остальные в той комнате испытают огорчение. А если комнат 3? 4?

Чтобы ход в одной комнате наложился на другой, нужно чтобы у этих ходов было время.
Сама по себе идея ограничения времени на ход хороша. Но делать её обязательной не нужно же?

В целом, любое ограничение на пользователя накладывается ровно в двух случаях:
- Когда нет ресурсов на то, что бы не накладывать ограничение.
- Когда ограничение необходимо для большего комфорта пользователя.

В данном случае , если мы говорим о не возможности играть в несколько игр, как об ограничении, то я не вижу проблем ни с одним из этих пунктов.

**Comment by MaxNacemit** [comment]
>мне не кажется, что лабиринт - это стратегическая игра

А зря не кажется.  Думать там еще как надо. 

>я не вижу ни одной вещи которая была бы сделана с таким расчетом

Как минимум база - то, кто в какой комнате, хранится с помощью поля room в таблице игроков, и все проверки наличия игрока в комнате идут от этого. 

>чтобы ход в одной комнате наложился на ход в другой, нужно, чтобы у ходов было время

Если у ходов время неограничено, в любом случае оно для остальных игроков в каждой из комнат не остановится. Пока игрок будет думать над ходом в одной комнате, игроки в другой будут страдать, ибо время хода каждого игрока увеличится в 2-3 раза.  Соответственно, игру в нескольких комнатах одновременно делать не надо, так как это заставляет других игроков страдать.

**Comment by gtivansan** [comment]
> Как минимум база - то, кто в какой комнате, хранится с помощью поля room в таблице игроков, и все проверки наличия игрока в комнате идут от этого.

Хорошо. Но. Куча кода? И самое ли лучшее наше решение было делать именно так?

**Comment by gtivansan** [comment]
> игроки в другой будут страдать

Да, это проблема.

Думаю нужна какая-нибудь мысль от Глеба. (Несколько игр сразу, насколько я понимаю - это его идея.)
